# Generated by Django 6.0.3 on 2026-03-16 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('members', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
