# Generated by Django 6.0.3 on 2026-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Nightmare', 'Nightmare')], max_length=20)),
                ('reward_gold', models.PositiveIntegerField()),
                ('reward_xp', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('heroes', models.ManyToManyField(related_name='quests', to='heroes.hero')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
