# Generated by Django 6.0.3 on 2026-03-16 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('hero_class', models.CharField(choices=[('Warrior', 'Warrior'), ('Mage', 'Mage'), ('Rogue', 'Rogue'), ('Paladin', 'Paladin'), ('Druid', 'Druid'), ('Hunter', 'Hunter'), ('Shaman', 'Shaman')], max_length=20)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_available_for_quests', models.BooleanField(default=True)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes', to='guilds.guild')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
